EPSILON = 1e-7

SEED = 42
BATCH_SIZE = 32

TITLE = "title"
OVERVIEW = "overview"
GENRE_IDS = "genre_ids"
GENRE_ID = "id"
GENRE_NAME = "name"

ACTION_GENRE = "Action"
ADVENTURE_GENRE = "Adventure"
ANIMATION_GENRE = "Animation"
COMEDY_GENRE = "Comedy"
CRIME_GENRE = "Crime"
DOCUMENTARY_GENRE = "Documentary"
DRAMA_GENRE = "Drama"
FAMILY_GENRE = "Family"
FANTASY_GENRE = "Fantasy"
HISTORY_GENRE = "History"
HORROR_GENRE = "Horror"
MUSIC_GENRE = "Music"
MYSTERY_GENRE = "Mystery"
ROMANCE_GENRE = "Romance"
SCIENCE_FICTION_GENRE = "Science Fiction"
TV_MOVIE_GENRE = "TV Movie"
THRILLER_GENRE = "Thriller"
WAR_GENRE = "War"
WESTERN_GENRE = "Western"

ALL_GENRES = [
    ACTION_GENRE,
    ADVENTURE_GENRE,
    ANIMATION_GENRE,
    COMEDY_GENRE,
    CRIME_GENRE,
    DOCUMENTARY_GENRE,
    DRAMA_GENRE,
    FAMILY_GENRE,
    FANTASY_GENRE,
    HISTORY_GENRE,
    HORROR_GENRE,
    MUSIC_GENRE,
    MYSTERY_GENRE,
    ROMANCE_GENRE,
    SCIENCE_FICTION_GENRE,
    TV_MOVIE_GENRE,
    THRILLER_GENRE,
    WAR_GENRE,
    WESTERN_GENRE,
]

PREDICTABLE_GENRES = [
    ACTION_GENRE,
    ADVENTURE_GENRE,
    ANIMATION_GENRE,
    COMEDY_GENRE,
    CRIME_GENRE,
    DRAMA_GENRE,
    FAMILY_GENRE,
    FANTASY_GENRE,
    HISTORY_GENRE,
    HORROR_GENRE,
    MUSIC_GENRE,
    MYSTERY_GENRE,
    ROMANCE_GENRE,
    SCIENCE_FICTION_GENRE,
    TV_MOVIE_GENRE,
    THRILLER_GENRE,
    WAR_GENRE,
    WESTERN_GENRE,
]

NARROW_PREDICTABLE_GENRES = [
    ACTION_GENRE,
    ADVENTURE_GENRE,
    ANIMATION_GENRE,
    COMEDY_GENRE,
    CRIME_GENRE,
    DRAMA_GENRE,
    FAMILY_GENRE,
    FANTASY_GENRE,
    HORROR_GENRE,
    MYSTERY_GENRE,
    ROMANCE_GENRE,
    SCIENCE_FICTION_GENRE,
    THRILLER_GENRE,
    WAR_GENRE,
]

HARD_CLASSES = [HISTORY_GENRE, MUSIC_GENRE, TV_MOVIE_GENRE, WESTERN_GENRE]

DATA_COLUMNS = [
    TITLE,
    OVERVIEW,
    GENRE_IDS,
    GENRE_ID,
    GENRE_NAME,
]
